### ISSUE TITLE
Improvements to Parallelization of Cypress Solution

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform-acceptance-tests#467] opened 2023-05-23 16:14 UTC
### Change Request Solution
Improvements have been identified relating to the QA Automation Project after the Parallelization of Cypress Spike solution was merged.

### What's the Expected Change?
- Improvements to the Parallelization of Cypress will be added/changed
- Add "Clean Up all Content" scenario to delete any remaining files at the end of the test

### What's the current functionality?
- See results from #461 

### What's the updated acceptance criteria?
To be added if necessary.
```gherkin
```

### Additional details / screenshot
- To do this I'll need to pull in code from each CMS file on deleting their individual test articles and files, then select each one. 
- It will also be conditional. For example, the CancerTypeHomePage article may/may not be there. The JS method would be something akin to "if (article-url) exists in the HTML, then mark the checkbox". 
- Each clean up scenario has this step to confirm the confirmation text says "2" or "3". I cannot check the specific number as the number of files I'll be removing varies considerably. 

### Related Tickets
* Original Story Ticket #461 
* Related Ticket #448

**Comment by santwuma** [comment] 2023-05-30 19:55
Duplicate of https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/463.

**Closed by santwuma** 2023-05-30 19:55 UTC
